services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./python-server/src:/app/src

  node-server:
    build:
      context: ./node-server/my-express-app
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./node-server/my-express-app/src:/usr/src/app/src
    working_dir: /usr/src/app
    command: ["npx", "nodemon", "src/server.js"]
